---
name: A9 Camera Server
version: 2.4
slug: a9-cam
description: A9 camera local server
url: https://github.com/bhtme/ha-addons
advanced: true
startup: application
init: false
homeassistant: 0.92.0b2
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 80
host_network: true
# ports_description:
#   80/tcp: The local server where the stream is exposed
#   29940/tcp: unknown
#   6123/tcp: unknown
#   53221/tcp: unknown
#   41234/tcp: unknown
ports:
  6123/tcp: 6123
  8002/tcp: 8002
  6123/udp: 6123
